// src/CompetitiveComparison.svelte
<section class="comparison">
	<div class="container">
		<h2 class="section-title">Why Lectere wins.</h2>
		
		<div class="comparison-table">
			<div class="comparison-row header">
				<div class="comparison-cell">Feature</div>
				<div class="comparison-cell">Docs</div>
				<div class="comparison-cell">Tours</div>
				<div class="comparison-cell lectere">Lectere</div>
			</div>
			<div class="comparison-row">
				<div class="comparison-cell">Real-time guidance</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell lectere">✅</div>
			</div>
			<div class="comparison-row">
				<div class="comparison-cell">Context-aware</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell lectere">✅</div>
			</div>
			<div class="comparison-row">
				<div class="comparison-cell">Auto-updates</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell lectere">✅</div>
			</div>
			<div class="comparison-row">
				<div class="comparison-cell">Works everywhere</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell">❌</div>
				<div class="comparison-cell lectere">✅</div>
			</div>
		</div>
	</div>
</section>

<style>
	.comparison {
		padding: 8rem 2rem;
		background: linear-gradient(180deg, #15111a 0%, #1a1520 100%);
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.comparison-table {
		max-width: 900px;
		margin: 0 auto;
		background: rgba(255, 255, 255, 0.02);
		border-radius: 24px;
		overflow: hidden;
		border: 1px solid rgba(155, 39, 76, 0.2);
	}
	
	.comparison-row {
		display: grid;
		grid-template-columns: 2fr 1fr 1fr 1fr;
		gap: 1px;
		background: rgba(255, 255, 255, 0.05);
	}
	
	.comparison-row.header {
		background: rgba(0, 0, 0, 0.3);
	}
	
	.comparison-cell {
		padding: 1.5rem;
		background: rgba(10, 10, 15, 0.9);
		display: flex;
		align-items: center;
		justify-content: center;
		text-align: center;
	}
	
	.comparison-row.header .comparison-cell {
		font-weight: 700;
		font-size: 1.1rem;
	}
	
	.comparison-cell.lectere {
		background: linear-gradient(135deg, rgba(155, 39, 76, 0.2), rgba(235, 51, 110, 0.2));
		border-left: 3px solid var(--razzmatazz);
		font-weight: 600;
		box-shadow: 0 0 30px rgba(235, 51, 110, 0.2);
	}
	
	@media (max-width: 768px) {
		.comparison-row {
			grid-template-columns: 1.5fr repeat(3, 1fr);
			font-size: 0.9rem;
		}
		
		.comparison-cell {
			padding: 1rem 0.5rem;
		}
	}
</style>

// src/components/CompetitiveComparison.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Check, X } from 'lucide-react';

const features = [
  'Real-time guidance',
  'Context-aware',
  'Auto-updates',
  'Works everywhere',
  'AI-powered',
];

const competitors = [
  { name: 'Docs' },
  { name: 'Tours' },
  { name: 'Videos' },
];

export function CompetitiveComparison() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative" ref={ref}>
      <div className="container px-6">
        <motion.h2
          className="text-4xl md:text-5xl lg:text-6xl font-display text-center mb-16"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          Why Lectere <span className="italic text-gradient">wins</span>.
        </motion.h2>

        <motion.div
          className="max-w-4xl mx-auto"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="bg-white rounded-2xl overflow-hidden border border-border shadow-sm">
            {/* Header */}
            <div className="grid grid-cols-5 gap-4 p-4 md:p-6 bg-secondary border-b border-border text-sm md:text-base font-medium">
              <div className="col-span-1">Feature</div>
              {competitors.map((c) => (
                <div key={c.name} className="text-center text-muted-foreground">{c.name}</div>
              ))}
              <div className="text-center text-gradient">Lectere</div>
            </div>

            {/* Features */}
            {features.map((feature, i) => (
              <motion.div
                key={feature}
                className="grid grid-cols-5 gap-4 p-4 md:p-6 border-b border-border last:border-0 items-center"
                initial={{ opacity: 0, x: -20 }}
                animate={isInView ? { opacity: 1, x: 0 } : {}}
                transition={{ duration: 0.4, delay: 0.3 + i * 0.1 }}
              >
                <div className="col-span-1 text-sm md:text-base">{feature}</div>
                {competitors.map((c) => (
                  <div key={`${c.name}-${i}`} className="flex justify-center">
                    <div className="w-8 h-8 rounded-full bg-red-50 flex items-center justify-center">
                      <X className="w-4 h-4 text-red-400" />
                    </div>
                  </div>
                ))}
                <div className="flex justify-center">
                  <motion.div
                    className="w-8 h-8 rounded-full bg-emerald-50 flex items-center justify-center"
                    initial={{ scale: 0 }}
                    animate={isInView ? { scale: 1 } : {}}
                    transition={{ delay: 0.5 + i * 0.1, type: 'spring', stiffness: 400 }}
                  >
                    <Check className="w-4 h-4 text-emerald-400" />
                  </motion.div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        <motion.p
          className="text-center text-muted-foreground mt-8 max-w-xl mx-auto"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ delay: 0.8 }}
        >
          The only solution that delivers real-time, intelligent guidance.
        </motion.p>
      </div>
    </section>
  );
}
