// src/Testimonials.svelte
<section class="testimonials">
	<div class="container">
		<h2 class="section-title">Real people. Real frustration. Real relief.</h2>
		
		<div class="testimonials-grid">
			<div class="testimonial-card">
				<p class="quote">Before Lectere, I spent hours searching for help. Now I just follow the visual guide and get work done.</p>
				<div class="author">— Sarah K., Small Business Owner</div>
			</div>
			<div class="testimonial-card">
				<p class="quote">As a senior, new software was terrifying. Lectere makes me feel confident and independent again.</p>
				<div class="author">— Robert M., Retired Teacher</div>
			</div>
			<div class="testimonial-card">
				<p class="quote">Our support tickets dropped 65% in the first month. Lectere pays for itself immediately.</p>
				<div class="author">— Jessica T., SaaS Product Lead</div>
			</div>
		</div>
	</div>
</section>

<style>
	.testimonials {
		padding: 8rem 2rem;
		background: linear-gradient(180deg, #15111a 0%, #1a1520 100%);
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.testimonials-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
		gap: 2rem;
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.testimonial-card {
		background: rgba(255, 255, 255, 0.03);
		border: 1px solid rgba(155, 39, 76, 0.3);
		border-radius: 24px;
		padding: 2.5rem;
		transition: all 0.3s ease;
	}
	
	.testimonial-card:hover {
		transform: translateY(-8px);
		border-color: rgba(235, 51, 110, 0.5);
		box-shadow: 0 12px 50px rgba(235, 51, 110, 0.2);
	}
	
	.quote {
		font-size: 1.2rem;
		line-height: 1.7;
		color: #e0e0e0;
		margin-bottom: 1.5rem;
		font-style: italic;
	}
	
	.quote::before {
		content: '"';
		color: var(--razzmatazz);
		font-size: 2rem;
		margin-right: 0.25rem;
	}
	
	.author {
		color: #888;
		font-size: 0.95rem;
	}
</style>

// src/components/Testimonials.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Star, Quote } from 'lucide-react';

const testimonials = [
  {
    quote: "Before Lectere, I spent hours searching for help. Now I just follow the visual guide and get work done.",
    author: 'Sarah K.',
    role: 'Small Business Owner',
    avatar: 'SK',
    gradient: 'from-rose-500 to-pink-500',
  },
  {
    quote: "As a senior, new software was terrifying. Lectere makes me feel confident and independent again.",
    author: 'Robert M.',
    role: 'Retired Teacher',
    avatar: 'RM',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    quote: "Our support tickets dropped 65% in the first month. Lectere pays for itself immediately.",
    author: 'Jessica T.',
    role: 'SaaS Product Lead',
    avatar: 'JT',
    gradient: 'from-cyan-500 to-blue-500',
  },
];

export function Testimonials() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative" ref={ref}>
      <div className="container px-6">
        <motion.h2
          className="text-4xl md:text-5xl lg:text-6xl font-display text-center mb-16"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          Real people. <span className="italic text-gradient">Real relief</span>.
        </motion.h2>

        <div className="grid md:grid-cols-3 gap-6 lg:gap-8 max-w-6xl mx-auto">
          {testimonials.map((testimonial, i) => (
            <motion.div
              key={testimonial.author}
              initial={{ opacity: 0, y: 40, rotate: i % 2 === 0 ? -2 : 2 }}
              animate={isInView ? { opacity: 1, y: 0, rotate: i % 2 === 0 ? -1 : 1 } : {}}
              transition={{ duration: 0.6, delay: 0.2 + i * 0.15, ease: [0.16, 1, 0.3, 1] }}
              whileHover={{ rotate: 0, scale: 1.02 }}
            >
              <Card className="glass-card h-full hover:border-primary/30 transition-all duration-300">
                <CardContent className="p-8 relative">
                  {/* Quote Icon */}
                  <div className="absolute -top-3 -left-1 w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
                    <Quote className="w-4 h-4 text-primary" />
                  </div>
                  
                  <p className="text-lg leading-relaxed mb-6 text-white/90">
                    "{testimonial.quote}"
                  </p>
                  
                  <div className="flex items-center gap-4">
                    <div className={`w-12 h-12 rounded-full bg-gradient-to-br ${testimonial.gradient} flex items-center justify-center text-white font-semibold`}>
                      {testimonial.avatar}
                    </div>
                    <div>
                      <div className="font-semibold">{testimonial.author}</div>
                      <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                    </div>
                  </div>

                  {/* Stars */}
                  <div className="flex gap-1 mt-4">
                    {[...Array(5)].map((_, j) => (
                      <Star key={j} className="w-4 h-4 fill-amber-400 text-amber-400" />
                    ))}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
