// src/WhoItsFor.svelte
<section class="who-its-for">
	<div class="container">
		<h2 class="section-title">Built for the people software forgot.</h2>
		
		<div class="personas-grid">
			<div class="persona-card">
				<div class="persona-icon">🎓</div>
				<h3>Students</h3>
				<p>Learning complex software for coursework without getting stuck</p>
			</div>
			<div class="persona-card">
				<div class="persona-icon">👵</div>
				<h3>Elderly users</h3>
				<p>Navigating technology with confidence and independence</p>
			</div>
			<div class="persona-card">
				<div class="persona-icon">💼</div>
				<h3>Small business owners</h3>
				<p>Managing tools without technical expertise or support</p>
			</div>
		</div>
	</div>
</section>

<style>
	.who-its-for {
		padding: 8rem 2rem;
		background: linear-gradient(180deg, #15111a 0%, #1a1520 100%);
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.personas-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
		gap: 2rem;
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.persona-card {
		background: rgba(255, 255, 255, 0.03);
		border: 1px solid rgba(155, 39, 76, 0.3);
		border-radius: 24px;
		padding: 3rem 2rem;
		text-align: center;
		transition: all 0.3s ease;
	}
	
	.persona-card:hover {
		transform: translateY(-8px);
		border-color: rgba(235, 51, 110, 0.5);
		box-shadow: 0 12px 50px rgba(235, 51, 110, 0.2);
	}
	
	.persona-icon {
		font-size: 4rem;
		margin-bottom: 1.5rem;
	}
	
	.persona-card h3 {
		font-size: 1.6rem;
		margin-bottom: 1rem;
	}
	
	.persona-card p {
		color: #b0b0b0;
		line-height: 1.6;
		font-size: 1.1rem;
	}
</style>

// src/components/WhoItsFor.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { GraduationCap, Heart, Briefcase } from 'lucide-react';

const personas = [
  { 
    icon: GraduationCap, 
    title: 'Students', 
    desc: 'Learning complex software for coursework without getting stuck',
    gradient: 'from-violet-500 to-purple-500'
  },
  { 
    icon: Heart, 
    title: 'Elderly users', 
    desc: 'Navigating technology with confidence and independence',
    gradient: 'from-rose-500 to-pink-500'
  },
  { 
    icon: Briefcase, 
    title: 'Small business owners', 
    desc: 'Managing tools without technical expertise or support',
    gradient: 'from-cyan-500 to-blue-500'
  },
];

export function WhoItsFor() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative" ref={ref}>
      {/* Background Pattern */}
      <div className="absolute inset-0 grid-pattern opacity-30" />
      
      <div className="container px-6 relative">
        <motion.h2
          className="text-4xl md:text-5xl lg:text-6xl font-display text-center mb-16"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          Built for the people{' '}
          <span className="text-gradient">software forgot</span>.
        </motion.h2>

        <div className="grid md:grid-cols-3 gap-6 lg:gap-8 max-w-5xl mx-auto">
          {personas.map((persona, i) => (
            <motion.div
              key={persona.title}
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.2 + i * 0.15, ease: [0.16, 1, 0.3, 1] }}
            >
              <Card className="glass-card h-full hover:border-primary/30 hover:-translate-y-3 transition-all duration-500 group relative overflow-hidden">
                <CardContent className="p-8 text-center relative z-10">
                  <motion.div
                    className={`w-20 h-20 rounded-2xl bg-gradient-to-br ${persona.gradient} flex items-center justify-center mx-auto mb-6 shadow-lg group-hover:scale-110 group-hover:rotate-3 transition-all duration-500`}
                  >
                    <persona.icon className="w-10 h-10 text-white" />
                  </motion.div>
                  <h3 className="text-2xl font-semibold mb-3">{persona.title}</h3>
                  <p className="text-muted-foreground leading-relaxed">{persona.desc}</p>
                </CardContent>
                
                {/* Hover Glow Effect */}
                <div className={`absolute inset-0 bg-gradient-to-br ${persona.gradient} opacity-0 group-hover:opacity-5 transition-opacity duration-500`} />
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
