// src/components/FinalCTA.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { ArrowRight, Sparkles } from 'lucide-react';

export function FinalCTA() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative overflow-hidden" ref={ref}>
      {/* Background */}
      <div className="absolute inset-0 mesh-gradient" />
      <div className="absolute inset-0 grid-pattern opacity-20" />
      
      {/* Animated Orbs */}
      <motion.div
        className="absolute top-1/2 left-1/4 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-gradient-to-r from-rose-500/20 to-fuchsia-500/20 blur-[100px]"
        animate={{ 
          scale: [1, 1.2, 1],
          opacity: [0.3, 0.5, 0.3]
        }}
        transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
      />
      <motion.div
        className="absolute top-1/2 right-1/4 -translate-y-1/2 w-[400px] h-[400px] rounded-full bg-gradient-to-l from-pink-500/20 to-purple-500/20 blur-[80px]"
        animate={{ 
          scale: [1.2, 1, 1.2],
          opacity: [0.2, 0.4, 0.2]
        }}
        transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut', delay: 1 }}
      />

      <div className="container px-6 relative">
        <motion.div
          className="max-w-3xl mx-auto text-center"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          <motion.h2
            className="text-4xl md:text-5xl lg:text-6xl xl:text-7xl font-display leading-[1.1] mb-6"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.1 }}
          >
            Stop teaching people<br />
            how to use software.
          </motion.h2>
          
          <motion.p
            className="text-2xl md:text-3xl text-muted-foreground mb-12"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            Let <span className="text-gradient font-medium">software teach them</span>.
          </motion.p>

          <motion.div
            className="flex flex-col sm:flex-row gap-4 justify-center"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.3 }}
          >
            <Button variant="gradient" size="xl" className="group">
              Request a Demo
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Button>
            <Button variant="outline" size="xl" className="border-white/20 hover:bg-white/5">
              <Sparkles className="w-5 h-5" />
              Start Free Trial
            </Button>
          </motion.div>

          <motion.p
            className="text-sm text-muted-foreground mt-8"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
            transition={{ delay: 0.5 }}
          >
            No credit card required • Setup in 5 minutes
          </motion.p>
        </motion.div>
      </div>
    </section>
  );
}

// src/FinalCTA.svelte
<section class="final-cta">
	<div class="container">
		<h2 class="cta-headline">Stop teaching people how to use software. Let software teach them.</h2>
		<div class="cta-buttons">
			<button class="btn-primary large">Request a Demo</button>
			<button class="btn-secondary large">Start Free Trial</button>
		</div>
	</div>
</section>

<style>
	.final-cta {
		padding: 10rem 2rem;
		background: linear-gradient(135deg, rgba(155, 39, 76, 0.15) 0%, rgba(235, 51, 110, 0.15) 100%);
		position: relative;
		overflow: hidden;
	}
	
	.final-cta::before {
		content: '';
		position: absolute;
		inset: 0;
		background: radial-gradient(circle at 30% 50%, rgba(155, 39, 76, 0.2) 0%, transparent 50%),
		            radial-gradient(circle at 70% 50%, rgba(235, 51, 110, 0.2) 0%, transparent 50%);
		animation: gradientPulse 6s ease-in-out infinite;
	}
	
	@keyframes gradientPulse {
		0%, 100% { opacity: 1; }
		50% { opacity: 0.6; }
	}
	
	.final-cta .container {
		position: relative;
		z-index: 1;
		text-align: center;
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.cta-headline {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		max-width: 900px;
		margin: 0 auto 3rem;
		line-height: 1.2;
		letter-spacing: -0.02em;
	}
	
	.cta-buttons {
		display: flex;
		gap: 1.5rem;
		justify-content: center;
		flex-wrap: wrap;
	}
	
	.btn-primary.large,
	.btn-secondary.large {
		padding: 1.25rem 3rem;
		font-size: 1.2rem;
	}
	
	.btn-primary {
		background: var(--razzmatazz);
		color: white;
		font-weight: 600;
		border: none;
		border-radius: 16px;
		cursor: pointer;
		transition: all 0.3s ease;
		box-shadow: 0 4px 20px rgba(235, 51, 110, 0.3);
	}
	
	.btn-primary:hover {
		transform: translateY(-2px) scale(1.02);
		box-shadow: 0 6px 30px rgba(235, 51, 110, 0.5);
	}
	
	.btn-secondary {
		background: transparent;
		color: white;
		font-weight: 600;
		border: 2px solid var(--amaranth-purple);
		border-radius: 16px;
		cursor: pointer;
		transition: all 0.3s ease;
	}
	
	.btn-secondary:hover {
		transform: translateY(-2px);
		background: rgba(155, 39, 76, 0.1);
		box-shadow: 0 0 20px rgba(155, 39, 76, 0.3);
	}
</style>
