// src/components/ProblemSection.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { TrendingDown, DollarSign } from 'lucide-react';

const stats = [
  { 
    value: '76%', 
    label: 'of users give up when stuck',
    icon: TrendingDown,
    gradient: 'from-rose-500 to-pink-500'
  },
  { 
    value: '$8.5T', 
    label: 'lost globally by 2030',
    icon: DollarSign,
    gradient: 'from-amber-500 to-orange-500'
  },
];

const frustrationFlow = [
  'Wrong click',
  'Search help',
  'Outdated video',
  'Still stuck',
  'Give up',
];

export function ProblemSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative overflow-hidden" ref={ref}>
      {/* Background Accent */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-primary/20 to-transparent" />
      
      <div className="container px-6">
        <motion.h2
          className="text-4xl md:text-5xl lg:text-6xl font-display text-center mb-16"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          Software shouldn't be{' '}
          <span className="relative">
            <span className="line-through decoration-primary/50 decoration-2">this hard</span>
          </span>
          .
        </motion.h2>

        {/* Stats Grid */}
        <div className="grid md:grid-cols-2 gap-6 max-w-3xl mx-auto mb-16">
          {stats.map((stat, i) => (
            <motion.div
              key={stat.value}
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.1 + i * 0.1, ease: [0.16, 1, 0.3, 1] }}
            >
              <Card className="glass-card hover:border-primary/30 hover:-translate-y-1 transition-all duration-300">
                <CardContent className="p-8 flex items-start gap-5">
                  <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${stat.gradient} flex items-center justify-center shrink-0`}>
                    <stat.icon className="w-7 h-7 text-white" />
                  </div>
                  <div>
                    <div className="text-4xl md:text-5xl font-display font-medium text-gradient mb-2">
                      {stat.value}
                    </div>
                    <div className="text-muted-foreground text-lg">{stat.label}</div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Frustration Flow */}
        <motion.div
          className="flex flex-wrap items-center justify-center gap-3 md:gap-4"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ duration: 0.8, delay: 0.5 }}
        >
          {frustrationFlow.map((step, i) => (
            <motion.div
              key={step}
              className="flex items-center gap-3 md:gap-4"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={isInView ? { opacity: 1, scale: 1 } : {}}
              transition={{ duration: 0.4, delay: 0.6 + i * 0.1, ease: [0.34, 1.56, 0.64, 1] }}
            >
              <span 
                className={`px-4 py-2 rounded-full text-sm md:text-base font-medium ${
                  i === frustrationFlow.length - 1 
                    ? 'bg-primary/20 text-primary border border-primary/30' 
                    : 'bg-destructive/10 text-red-400 border border-red-500/20'
                }`}
              >
                {step}
              </span>
              {i < frustrationFlow.length - 1 && (
                <motion.span 
                  className="text-muted-foreground text-lg"
                  initial={{ opacity: 0, x: -10 }}
                  animate={isInView ? { opacity: 1, x: 0 } : {}}
                  transition={{ delay: 0.7 + i * 0.1 }}
                >
                  →
                </motion.span>
              )}
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

// src/ProblemSection.svelte
<section class="problem">
	<div class="container">
		<h2 class="section-title">Software shouldn't be this hard.</h2>
		
		<div class="stats-grid">
			<div class="stat-card">
				<div class="stat-number">76%</div>
				<div class="stat-label">of users give up when stuck</div>
			</div>
			<div class="stat-card">
				<div class="stat-number">Days or Weeks</div>
				<div class="stat-label">Onboarding takes</div>
			</div>
			<div class="stat-card">
				<div class="stat-number">$8.5T</div>
				<div class="stat-label">lost globally by 2030</div>
			</div>
		</div>
		
		<div class="frustration-flow">
			<div class="flow-step error">Wrong click</div>
			<div class="flow-arrow">→</div>
			<div class="flow-step error">Search help</div>
			<div class="flow-arrow">→</div>
			<div class="flow-step error">Watch outdated video</div>
			<div class="flow-arrow">→</div>
			<div class="flow-step error">Still stuck</div>
			<div class="flow-arrow">→</div>
			<div class="flow-step highlight">Give up</div>
		</div>
	</div>
</section>

<style>
	.problem {
		padding: 8rem 2rem;
		background: linear-gradient(180deg, #15111a 0%, #1a1520 100%);
		position: relative;
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.stats-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
		gap: 2rem;
		margin-bottom: 5rem;
	}
	
	.stat-card {
		background: rgba(255, 255, 255, 0.03);
		border: 1px solid rgba(155, 39, 76, 0.2);
		border-radius: 24px;
		padding: 3rem 2rem;
		text-align: center;
		backdrop-filter: blur(10px);
		transition: all 0.3s ease;
	}
	
	.stat-card:hover {
		transform: translateY(-5px);
		border-color: rgba(155, 39, 76, 0.5);
		box-shadow: 0 8px 40px rgba(155, 39, 76, 0.2);
	}
	
	.stat-number {
		font-size: clamp(2.5rem, 5vw, 4rem);
		font-weight: 800;
		background: linear-gradient(135deg, var(--razzmatazz), var(--amaranth-purple));
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
		margin-bottom: 1rem;
	}
	
	.stat-label {
		font-size: 1.1rem;
		color: #b0b0b0;
	}
	
	.frustration-flow {
		display: flex;
		align-items: center;
		justify-content: center;
		flex-wrap: wrap;
		gap: 1rem;
		padding: 2rem;
	}
	
	.flow-step {
		padding: 1rem 1.5rem;
		border-radius: 12px;
		font-weight: 600;
		font-size: 1rem;
	}
	
	.flow-step.error {
		background: rgba(155, 39, 76, 0.15);
		border: 1px solid var(--amaranth-purple);
		color: #ff8fa3;
	}
	
	.flow-step.highlight {
		background: rgba(235, 51, 110, 0.2);
		border: 2px solid var(--razzmatazz);
		color: var(--razzmatazz);
	}
	
	.flow-arrow {
		color: var(--razzmatazz);
		font-size: 1.5rem;
	}
</style>
