// src/components/SocialImpact.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Quote } from 'lucide-react';

export function SocialImpact() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative overflow-hidden bg-secondary/50" ref={ref}>
      <div className="container px-6 relative">
        <motion.div
          className="max-w-3xl mx-auto text-center"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          <motion.h2
            className="text-4xl md:text-5xl lg:text-6xl font-display mb-8"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.1 }}
          >
            The digital accessibility{' '}
            <span className="text-gradient">crisis</span>.
          </motion.h2>

          <motion.p
            className="text-xl text-muted-foreground leading-relaxed mb-6"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            Every day, millions of people are left behind by software that assumes 
            everyone learns the same way. Broken onboarding experiences waste countless 
            hours and exclude those who need technology most.
          </motion.p>

          <motion.p
            className="text-xl leading-relaxed mb-12"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.3 }}
          >
            <strong className="text-foreground">Lectere exists to make software accessible to everyone</strong> — 
            regardless of age, technical skill, or learning style.
          </motion.p>

          <motion.div
            className="bg-white rounded-2xl p-8 md:p-10 relative border border-border shadow-sm"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={isInView ? { opacity: 1, scale: 1 } : {}}
            transition={{ duration: 0.8, delay: 0.4 }}
          >
            <div className="absolute -top-4 left-1/2 -translate-x-1/2 w-10 h-10 rounded-full bg-gradient-to-br from-[#eb336e] to-[#9b274c] flex items-center justify-center">
              <Quote className="w-5 h-5 text-white" />
            </div>
            <p className="text-2xl md:text-3xl font-display italic leading-relaxed text-foreground">
              Technology should adapt to humans, not the other way around.
            </p>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
}

// src/SocialImpact.svelte
<section class="social-impact">
	<div class="container">
		<h2 class="section-title">The digital accessibility crisis.</h2>
		
		<div class="impact-content">
			<p class="impact-text">
				Every day, millions of people are left behind by software that assumes everyone learns the same way. Broken onboarding experiences waste countless hours and exclude those who need technology most.
			</p>
			<p class="impact-text">
				Lectere exists to make software accessible to everyone — regardless of age, technical skill, or learning style.
			</p>
		</div>
	</div>
</section>

<style>
	.social-impact {
		padding: 8rem 2rem;
		background: linear-gradient(135deg, rgba(155, 39, 76, 0.1) 0%, rgba(235, 51, 110, 0.1) 100%);
		position: relative;
		overflow: hidden;
	}
	
	.social-impact::before {
		content: '';
		position: absolute;
		inset: 0;
		background: linear-gradient(45deg, transparent 30%, rgba(155, 39, 76, 0.05) 50%, transparent 70%);
		animation: shimmer 8s ease-in-out infinite;
	}
	
	@keyframes shimmer {
		0%, 100% { transform: translateX(-100%); }
		50% { transform: translateX(100%); }
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.impact-content {
		max-width: 800px;
		margin: 0 auto;
		position: relative;
		z-index: 1;
	}
	
	.impact-text {
		font-size: 1.4rem;
		line-height: 1.8;
		margin-bottom: 2rem;
		color: #e0e0e0;
		text-align: center;
	}
</style>
