// src/components/WhatIsLectere.tsx
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Target, RefreshCw, Sparkles } from 'lucide-react';

const features = [
  { 
    icon: Target, 
    title: 'Real-time on-screen guidance', 
    desc: 'Visual highlights show exactly where to click',
    gradient: 'from-[#eb336e] to-[#9b274c]'
  },
  { 
    icon: RefreshCw, 
    title: 'Cross-software intelligence', 
    desc: 'Works across any application',
    gradient: 'from-[#c43278] to-[#832558]'
  },
  { 
    icon: Sparkles, 
    title: 'Always-up-to-date workflows', 
    desc: 'Automatically adapts to UI changes',
    gradient: 'from-[#e8556b] to-[#c43278]'
  },
];

export function WhatIsLectere() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="section-padding relative bg-secondary/50" ref={ref}>
      <div className="container px-6 relative">
        <motion.h2
          className="text-4xl md:text-5xl lg:text-6xl font-display text-center mb-8"
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          Meet <span className="text-gradient">Lectere</span>.
        </motion.h2>

        <motion.div
          className="max-w-3xl mx-auto text-center mb-16"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
        >
          <p className="text-xl text-muted-foreground leading-relaxed">
            Lectere is an AI assistant that appears inside any software and guides users 
            visually on their real screen — showing exactly where to click and what to do 
            without leaving the app.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.3 + i * 0.1, ease: [0.16, 1, 0.3, 1] }}
            >
              <Card className="h-full hover:border-primary/30 hover:-translate-y-2 transition-all duration-300 group shadow-sm hover:shadow-md bg-white">
                <CardContent className="p-8 text-center">
                  <motion.div
                    className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mx-auto mb-6 shadow-lg group-hover:scale-110 transition-transform duration-300`}
                    whileHover={{ rotate: 5 }}
                  >
                    <feature.icon className="w-8 h-8 text-white" />
                  </motion.div>
                  <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.desc}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/WhatIsLectere.svelte
<section class="what-is">
	<div class="container">
		<h2 class="section-title">Meet Lectere.</h2>
		
		<div class="definition">
			<p>
				Lectere is an AI assistant that appears inside any software and guides users visually on their real screen — showing exactly where to click and what to do without leaving the app.
			</p>
		</div>
		
		<div class="features-grid">
			<div class="feature-card">
				<div class="feature-icon">🎯</div>
				<h3>Real-time on-screen guidance</h3>
				<p>Visual highlights show exactly where to click</p>
			</div>
			<div class="feature-card">
				<div class="feature-icon">⚡</div>
				<h3>Auto-generated steps</h3>
				<p>AI creates workflows automatically</p>
			</div>
			<div class="feature-card">
				<div class="feature-icon">🔄</div>
				<h3>Cross-software intelligence</h3>
				<p>Works across any application</p>
			</div>
			<div class="feature-card">
				<div class="feature-icon">✨</div>
				<h3>Always-up-to-date workflows</h3>
				<p>Automatically adapts to UI changes</p>
			</div>
		</div>
	</div>
</section>

<style>
	.what-is {
		padding: 8rem 2rem;
		background: linear-gradient(180deg, #1a1520 0%, #15111a 100%);
	}
	
	.container {
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.section-title {
		font-size: clamp(2rem, 6vw, 3.5rem);
		font-weight: 800;
		text-align: center;
		margin-bottom: 4rem;
		letter-spacing: -0.02em;
	}
	
	.definition {
		max-width: 800px;
		margin: 0 auto 5rem;
		text-align: center;
	}
	
	.definition p {
		font-size: 1.3rem;
		line-height: 1.8;
		color: #d0d0d0;
	}
	
	.features-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
		gap: 2rem;
		max-width: 1200px;
		margin: 0 auto;
	}
	
	.feature-card {
		background: rgba(255, 255, 255, 0.02);
		border: 1px solid rgba(155, 39, 76, 0.3);
		border-radius: 24px;
		padding: 2.5rem;
		backdrop-filter: blur(10px);
		transition: all 0.3s ease;
	}
	
	.feature-card:hover {
		transform: translateY(-5px);
		border-color: rgba(235, 51, 110, 0.5);
		box-shadow: 0 0 40px rgba(155, 39, 76, 0.3);
	}
	
	.feature-icon {
		font-size: 3rem;
		margin-bottom: 1rem;
	}
	
	.feature-card h3 {
		font-size: 1.4rem;
		margin-bottom: 1rem;
		color: #ffffff;
	}
	
	.feature-card p {
		color: #b0b0b0;
		line-height: 1.6;
	}
</style>
